### ISSUE TITLE
Google DNS Trouble

### ISSUE THREAD

**Issue by madmanmatt** [binhex/arch-openvpn#1]
Hi @binhex I am having an issue with your Docker projects that depend on this repo. Specifically arch-delugevpn and arch-sabnzbdvpn. 

The problem is that I have to block the Google DNS servers on my network because I use a Netflix region switching service (Unblock-Us). Some new devices such as Chromecasts and Rokus have the Google DNS servers hard coded in their firmware and will only fallback to my desired DNS provider (Unblock-Us) if the Google servers can't be reached. While this makes my Netflix region switching service work, it breaks your wonderful docker containers. I know this is an edge case but I'm wondering if you'd consider changing the DNS provider in your script from Google to a different public DNS service like Level3 or similar. Thanks for considering this. I'd be happy to make change this and submit a pull request if you'd be interested.

**Comment by binhex** [comment]
this is now resolved, please use the NAME_SERVERS env var via the docker run command if you want to define them.
