### ISSUE TITLE
ping and ping-restart ignored

### ISSUE THREAD

**Issue by DeadWalkingDeath** [binhex/arch-openvpn#4]
Hi binhex,

I'm having issues with the docker image recently. The VPN connection is constantly restarting. After a bit of investigation, I've noticed that the pushes from the server for ping and ping-restart get ignored now. The default option --keepalive 10 60 never changes and therefore the timeouts between client and server are different, which leads to the reconnects.

`Sat Nov 25 17:12:37 2017 Pushed option removed by filter: 'ping 3'`
`Sat Nov 25 17:12:37 2017 Pushed option removed by filter: 'ping-restart 10'`

So ignoring those options may not be the best way. I've temporarily removed them and everthing works fine.

**Comment by binhex** [comment]
hi DeadWalkingDeath,

so to be clear, are you saying that having a openvpn option defined as:-

`--keepalive 10 60`

means that you get repeated disconnections and reconnections because there is a mismatch between the pushed options of --ping and --ping-restart, and the --keepalive value i have defined?.

im suprised if that is true, especially as the values i use are greater than the ones pushed to the client, any chance you can post a small section of your log showing the connection/re-connection issue?

**Comment by DeadWalkingDeath** [comment]
`--keepalive 10 60`
is short for
`--ping 10`
`--ping restart 60`

So when using this and
`--pull-filter ignore 'ping' --pull-filter ignore 'ping-restart'`
it means that those two values can never change.

My VPN provider is expecting values of 3 (ping) and 10 (ping-restart), which the server tries to push to the client. But those filters will not allow the client to use this values.

So the server is waiting for a ping every 3 seconds, but the client will only send a ping every 10 seconds. Or maybe it's the client who is waiting for the ping, I'm not sure.
But either way the connection will always restart if nothing happens for a few seconds.

**Comment by DeadWalkingDeath** [comment]
I've uploaded a small section of the log file, where you can see the reconnects.
They happen at:
14:00:16 - 14:02:05 - 14:05:24 - 14:06:52 - 14:08:19
It goes like that for hours.

Since I've removed the options
 `--pull-filter ignore 'ping' --pull-filter ignore 'ping-restart'`
the reconnect didn't happen anymore.
[vpn.log](https://github.com/binhex/arch-openvpn/files/1511539/vpn.log)

**Comment by binhex** [comment]
Thanks for the logs, so yes it looks like what might be happening is the remote end is forcing pings every 3 secs from the client, it then monitors for these pings from the client and if it doesn't receive one within the specified time then it assumes the client is dead and closes the tunnel.

This is all assumptions ive made by reading the openvpn man and looking at your log so i could be wrong here but im willing to bet thats probably how its working. So with that in mind i will need to remove the filter of those two options and also remove the lines of code to delete the ping and ping-restart from the ovpn file, i will leave in the --keepalive flag but this will be overridden as it did in the past by pushed options, sound ok?.

**Comment by DeadWalkingDeath** [comment]
I'm no OpenVPN expert either, but it really looks like that is what happens.
Yes, I think it should work with the changes you described.
Thank you for looking into this.

**Comment by DeadWalkingDeath** [comment]
I've tested the latest changes and everything seems to work fine again.
Thanks
