### ISSUE TITLE
hosts file gets overwritten on restart

### ISSUE THREAD

**Issue by thepiwo** [binhex/arch-openvpn#5]
Hey, I noticed the /etc/hosts file will get overwritten on each restart, is there a way to keep manually added hosts lines?

I am using the https://github.com/binhex/arch-delugevpn variant, but I guess the corresponding code is in this repository

**Comment by binhex** [comment]
The hosts file needs to be edited on startup to inject the name to ip of the endpoint you're connecting to, keep in mind this is the hosts file inside the container, not on your host machine, can i ask why you want to add lines to the hosts file?.

**Comment by thepiwo** [comment]
yes I found the injection. One tracker I use is only reachable with the ip set to a specific hostname over the hosts file

**Comment by binhex** [comment]
i think for now this wont get fixed, its a very specific issue you have here, feel free to fork if you want to have a go yourself.
