### ISSUE TITLE
Cannot start container, tini outputs program usage

### ISSUE THREAD

**Issue by UntouchedWagons** [binhex/arch-openvpn#7]
When I start this docker on my unraid machine the container immediately exits with tini writing its usage to the log:

    tini (tini version 0.18.0 - git.fec3683)
    Usage: tini [OPTIONS] PROGRAM -- [ARGS] | --version

    Execute a program under the supervision of a valid init process (tini)

    Command line options:

    --version: Show version and exit.
    -h: Show this help message and exit.
    -s: Register as a process subreaper (requires Linux >= 3.4).
    -p SIGNAL: Trigger SIGNAL when parent dies, e.g. "-p SIGKILL".
    -v: Generate more verbose output. Repeat up to 3 times.
    -w: Print a warning when processes are getting reaped.
    -g: Send signals to the child's process group.
    -e EXIT_CODE: Remap EXIT_CODE (from 0 to 255) to 0.
    -l: Show license and exit.

    Environment variables:

    TINI_SUBREAPER: Register as a process subreaper (requires Linux >= 3.4).
    TINI_VERBOSITY: Set the verbosity level (default: 1).
    TINI_KILL_PROCESS_GROUP: Send signals to the child's process group.

**Comment by binhex** [comment]
Your can't use this image on its own, it's an intermediate image used by delugevpn, sabbzbdvpn and rtorrentvpn.
